# Dependencies
markdown:         kramdown
highlighter:      rouge
# This will require each of these plugins automatically.
plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Vu Nguyen
tagline:          'Personal Blog: Tech & Life'
description:      'computational statistician'
baseurl:          https://vn2616.github.io/

paginate:         5

# Custom vars
