# Dependencies
markdown:         kramdown
highlighter:      pygments
# This will require each of these plugins automatically.
plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Vu Nguyen
tagline:          'Personal Site'
description:      'A computational statistician'
baseurl:          https://vn2616.github.io/

paginate:         5

# Custom vars

socials:
  github:
    link: https://github.com/vn2616
    icon: github
  facebook:
    link: https://facebook.com/vn2616
    icon: facebook-square
  email:
    link: mailto:vn2616@gmail.com
    icon: envelope
